### ISSUE TITLE
BAAObject missing

### ISSUE THREAD

**Issue by eugeniobaglieri** [baasbox/Swift-SDK#1]
Good evening, is the missing of BAAObject class, an "intended feature" or it will be implemented in future?
If I want create a class for my model should I implement every init method and encode method like in User class?

**Comment by LucaCardelli** [comment]
The Swift SDK is not a port of the Objective-C SDK, therefore they differ in some functions.

The missing of BAAObject is intended as it give you full flexibility on how you want to use the data retrieved from BaasBox.

You can easily use this init method in your model to populate your object:

    init(withDictionary dict: [String: AnyObject]) {
         self.key = dict["key"] 
    }

You dont need the encode and decode methods if you dont want to serialize the data.

Luca
